version: "3"

x-uffizzi:
  ingress:
    service: frontend
    port: 8000

services:
  
  backend:
    image: ${MEDUSA_IMAGE}
    environment:
      DATABASE_URL: postgres://postgres:postgres@0.0.0.0:5432/medusa-docker
      REDIS_URL: redis://0.0.0.0
      NODE_ENV: development
      JWT_SECRET: something
      COOKIE_SECRET: something
      PORT: 9000
    ports: 
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 4000M

  frontend:
    image: ${STOREFRONT_IMAGE}
    ports:
    - "8000:8000"
    entrypoint: /bin/sh
    command: ["-c", "apk add wait4ports && wait4ports tcp://0.0.0.0:5432 && yarn start"]
    deploy:
      resources:
        limits:
          memory: 2000M
    
  postgres: 
    image: postgres:10.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: medusa-docker
    deploy:
      resources:
        limits:
          memory: 1000M

  redis:
    image: redis
    expose:
      - "6379:6379"

volumes:
  node_modules:
  frontend_node_modules:
